// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrKVNa5-iR50O_jYB41bLj3bWQnSr04rE',
    appId: '1:678110347945:web:8c5a3b9ff8e3faec121fb8',
    messagingSenderId: '678110347945',
    projectId: 'ict-helpdesk-5dd9d',
    authDomain: 'ict-helpdesk-5dd9d.firebaseapp.com',
    storageBucket: 'ict-helpdesk-5dd9d.firebasestorage.app',
    measurementId: 'G-X4KY232JD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADUKQn6GN8j_a8eCednEzY0Td1LoSiEvY',
    appId: '1:678110347945:android:ca1285e071b30d3e121fb8',
    messagingSenderId: '678110347945',
    projectId: 'ict-helpdesk-5dd9d',
    storageBucket: 'ict-helpdesk-5dd9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSbWm0bAjNaOHgu7erlFU9j0f0ydV9HXw',
    appId: '1:678110347945:ios:004af2e84e2ebbfa121fb8',
    messagingSenderId: '678110347945',
    projectId: 'ict-helpdesk-5dd9d',
    storageBucket: 'ict-helpdesk-5dd9d.firebasestorage.app',
    iosBundleId: 'com.example.ictHelpdesk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSbWm0bAjNaOHgu7erlFU9j0f0ydV9HXw',
    appId: '1:678110347945:ios:004af2e84e2ebbfa121fb8',
    messagingSenderId: '678110347945',
    projectId: 'ict-helpdesk-5dd9d',
    storageBucket: 'ict-helpdesk-5dd9d.firebasestorage.app',
    iosBundleId: 'com.example.ictHelpdesk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEJIhWKrfRl9JRfGKO6OmTO7KfeCFuf9s',
    appId: '1:678110347945:web:119478e823236887121fb8',
    messagingSenderId: '678110347945',
    projectId: 'ict-helpdesk-5dd9d',
    authDomain: 'ict-helpdesk-5dd9d.firebaseapp.com',
    storageBucket: 'ict-helpdesk-5dd9d.firebasestorage.app',
    measurementId: 'G-5V2MGFEX49',
  );
}
